// Welcome to Turtletoy!
//
// Turtletoy is a community for creative coding. We believe the joy
// is in the craft.
//
// ---------------------------------------------------------------
// A NOTE ON AI:
// Please do not publish code entirely generated by AI.
// We want to see YOUR creativity, your mistakes, and your logic.
// If you use AI to learn, try to rewrite the code yourself before
// sharing, so others can learn from your human approach.
// ---------------------------------------------------------------
//
// API Reference: https://turtletoy.net/syntax

Canvas.setpenopacity(1);

const stepSize = 2; // min=1 max=100 step=10  Shape Placing
const t = new Turtle();
t.penup();
t.goto(-350, -150);
t.pendown();

//gridOne()
gridOneWithRects();
gridTwo();

// The walk function will be called until it returns false.
function walk(i) {
  return i < 20;
}

function gridTwo() {
  t.penup();
  t.goto(-300, 100);
  t.setheading(0);
  t.pendown();
  t.forward(20);

  for (let i = 0; i < 20; i++) {
    t.left(45);

    for (let j = 0; j < 400 / stepSize; j++) {
      t.penup();
      t.forward(stepSize);
      t.pendown();
      abc(t.pos()[0], t.pos()[1]);
    }

    t.penup();
    t.backward(400);
    t.right(45);
    t.forward(20);
    t.pendown();
  }
}
function gridOneWithRects() {
  t.penup();
  t.goto(-350, -150);
  t.setheading(0);
  t.pendown();
  for (let i = 0; i < 20; i++) {
    t.right(45);

    for (let j = 0; j < 400 / stepSize; j++) {
      t.penup();
      t.forward(stepSize);
      t.pendown();
      abc(t.pos()[0], t.pos()[1]);
    }

    t.penup();
    t.backward(400);
    t.left(45);
    t.forward(20);
    t.pendown();
  }
}

function gridOne() {
  for (let i = 0; i < 20; i++) {
    t.right(45);
    t.forward(400);
    t.penup();
    t.backward(400);
    t.left(45);
    t.forward(20);
    t.pendown();
  }
}

function abc2(x, y) {
  t.penup();
  t.goto(x + 2, y - 4);
  t.pendown();
  for (let i = 0; i < 4; i++) {
    t.right(90);
    t.forward(8);
  }
  t.penup();
  t.goto(x, y);
  t.pendown();
}

function abc(x, y) {
  const prevHeading = t.heading();
  t.right(45);
  t.backward(5);
  t.forward(10);
  t.penup();
  t.backward(5);
  t.left(45);
  t.setheading(prevHeading);
  t.pendown();
}
