// Welcome to Turtletoy!
//
// Turtletoy is a community for creative coding. We believe the joy
// is in the craft.
//
// ---------------------------------------------------------------
// A NOTE ON AI:
// Please do not publish code entirely generated by AI.
// We want to see YOUR creativity, your mistakes, and your logic.
// If you use AI to learn, try to rewrite the code yourself before
// sharing, so others can learn from your human approach.
// ---------------------------------------------------------------
//
// API Reference: https://turtletoy.net/syntax

Canvas.setpenopacity(1);

const stepSize = 2; // min=1 max=100 step=10  Shape Placing
const gridLenght = 860; // min=400 max=1000 step=50  Grid Length
const chaosLevel = 0; // min=0, max=2, step=1, (Zero, Some, All)

const chaosValues = [45, 30];

const t = new Turtle();
t.penup();
t.goto(-350, -150);
t.pendown();

gridOne();
gridTwo();

// The walk function will be called until it returns false.
function walk(i) {
  return i < 20;
}

function gridTwo() {
  t.penup();
  t.goto(-300, 100);
  t.setheading(0);
  t.pendown();
  t.forward(20);

  for (let i = 0; i < 20; i++) {
    t.left(45);

    for (let j = 0; j < gridLenght / stepSize; j++) {
      t.penup();
      t.forward(stepSize);
      t.pendown();
      abc(t.pos()[0], t.pos()[1]);
    }

    t.penup();
    t.backward(gridLenght);
    t.right(45);
    t.forward(20);
    t.pendown();
  }
}
function gridOne() {
  t.penup();
  t.goto(-350, -150);
  t.setheading(0);
  t.pendown();
  for (let i = 0; i < 20; i++) {
    t.right(45);

    for (let j = 0; j < gridLenght / stepSize; j++) {
      t.penup();
      t.forward(stepSize);
      t.pendown();
      abc(t.pos()[0], t.pos()[1]);
    }

    t.penup();
    t.backward(gridLenght);
    t.left(45);
    t.forward(20);
    t.pendown();
  }
}

function getChaos() {
  if (chaosLevel > 1) {
    return Math.floor(Math.random() * 361);
  } else if (chaosLevel > 0) {
    var random_boolean = Math.random() < 0.5;

    if (Math.random() < 0.5) {
      return chaosValues[0];
      // return chaosValues[chaosLevel+34]
    }

    return chaosValues[chaosLevel];
  }
  return chaosValues[chaosLevel];
}

function abc(x, y) {
  const angle = getChaos();
  const prevHeading = t.heading();

  t.right(angle);
  t.backward(5);
  t.forward(10);
  t.penup();
  t.backward(5);
  //t.left(angle);
  t.setheading(prevHeading);
  t.pendown();
}
